language: python
python:
  - "2.7"
# command to install dependencies
install: 
    - sudo apt-get install gsl-bin libgsl0-dev libgsl0ldbl
    - sudo apt-get install python-tables
    - "pip install -r requirements.txt"
before_install: sudo apt-get update
# command to run tests
script: nosetests
